<?php //echo Mage::getUrl('virtualproduct/virtualproduct/add'); ?>
<div class="row">
  <div class="col-lg-12">
    <div class="page-header">
      <h1 id="forms">Your Idea</h1>
    </div>
  </div>
</div>

<!--FORM-->
<div class="row">
  <div class="col-lg-6">
    <div class="well bs-component">
      <form class="form-horizontal" method="post" action="<?php echo Mage::getUrl('youridea/index/add'); ?>">
        <fieldset>
          <legend>Legend</legend>
          <div class="form-group">
            <label for="input-product-name" class="col-lg-2 control-label">Idea name</label>
            <div class="col-lg-10">
              <input type="text" name="idea[name]" class="form-control" id="input-product-name" placeholder="Name" required>
            </div>
          </div>
          <div class="form-group">
            <label for="short-description" class="col-lg-2 control-label">Short description</label>
            <div class="col-lg-10">
              <textarea name="idea[shortDescription]" class="form-control" rows="3" id="short-description" required></textarea>
              <span class="help-block">Please enter short description your idea</span>
            </div>
          </div>
          <div class="form-group">
            <label for="description" class="col-lg-2 control-label">Description</label>
            <div class="col-lg-10">
              <textarea name="idea[description]" class="form-control" rows="3" id="description" required></textarea>
              <span class="help-block">Please enter full description your idea</span>
            </div>
          </div>
          <div class="form-group">
            <div class="col-lg-10 col-lg-offset-2">
              <button type="reset" class="btn btn-default">Cancel</button>
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
          </div>
        </fieldset>
      </form>
    </div>
  </div>
</div>
<!--END FORM-->